version: 2

# Specify the build environment
build:
  os: "ubuntu-22.04"  # The default OS for Read the Docs builds
  tools:
    python: "3.9"  # Specify the Python version for the build

# Documentation generator configuration
sphinx:
  configuration: docs/conf.py

# Install dependencies
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# Build settings
formats:
  - html
  - pdf
  - epub
